project_name: repos

builds:
  - id: default
    goos:
      - linux
    goarch:
      - amd64

nfpms:
  - id: repos
    formats:
    - deb
    package_name: repos
    file_name_template: "{{ .PackageName }}_{{ .Version }}_{{ .Arch }}"
    homepage: "https://github.com/MiguelRodo/repos"
    description: "Cross-platform CLI for managing multiple related Git repositories as a unified workspace"
    license: "MIT"
    maintainer: "Miguel Rodo"
    formats:
      - deb
    bindir: /usr/bin

archives:
  - format: tar.gz
