project:
  type: website

website:
  title: "repos"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: install.qmd
        text: Installation
      - href: repos-list.qmd
        text: repos.list
      - href: setup.qmd
        text: repos setup
      - href: pipelines.qmd
        text: Running Pipelines

format:
  html:
    theme: cosmo
